external:
  globus:
    redirect:
    clientID:
    nodes:
  wget: https://esgf-node.llnl.gov/esg-search/wget
  search: https://esgf-node.llnl.gov/esg-search/search
  nodeStatus: https://aims2.llnl.gov/metagrid-backend/proxy/status
  solr: https://esgf-fedtest.llnl.gov/solr
  keycloak:
    url: https://login.esgf.io/
    realm: esgf
    clientID: metagrid-llnl
  hotjar:
    id:
    sv:
  googleAnalyticsTrackingID:

django:
  replicaCount: 1

  adminURL: panel/
  corsOriginWhitelist: ""
  secretKey:

  image:
    repository: ghcr.io/aims-group/metagrid-backend
    pullPolicy: Always
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  migrateJob:
    enabled: true

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  service:
    type: ClusterIP
    port: 5000

react:
  replicaCount: 1

  image:
    repository: ghcr.io/aims-group/metagrid-frontend
    pullPolicy: Always
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  service:
    type: ClusterIP
    port: 3000

  monitoring:
    enabled: false

ingress:
  enabled: false
  annotations: {}
  labels: {}

  react:
    host:
    path: /metagrid

  django:
    host:
    path: /metagrid-backend

postgresql:
  enabled: true

  persistence:
    enabled: false

  postgresql:
    replicaCount: 1
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    password: pgpass
    repmgrPassword: repmgrpass

  pgpool:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    adminPassword: pgpooladminpass

extraManifests: {}
