apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metagrid.fullname" . }}-react
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
data:
  PUBLIC_URL: {{ .Values.ingress.react.path }}
  REACT_APP_METAGRID_API_URL: http://{{ include "metagrid.fullname" . }}-django
  REACT_APP_PREVIOUS_URL: {{ .Values.previousURL }}
  {{- with .Values.external.globus }}
  REACT_APP_GLOBUS_REDIRECT: {{ .redirect }}
  REACT_APP_CLIENT_ID: {{ .clientID }}
  REACT_APP_GLOBUS_NODES: {{ .nodes }}
  {{- end }}
  REACT_APP_WGET_API_URL: {{ .Values.external.wget }}
  REACT_APP_SEARCH_URL: {{ .Values.external.search }}
  REACT_APP_ESGF_NODE_STATUS_URL: {{ .Values.external.nodeStatus }}
  {{- with .Values.external.keycloak }}
  REACT_APP_KEYCLOAK_REALM: {{ .realm }}
  REACT_APP_KEYCLOAK_URL: {{ .url }}
  REACT_APP_KEYCLOAK_CLIENT_ID: {{ .clientID }}
  {{- end }}
  {{- with .Values.external.hotjar }}
  REACT_APP_HOTJAR_ID: {{ .id }}
  REACT_APP_HOTJAR_SV: {{ .sv }}
  {{- end }}
