apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metagrid.fullname" . }}-react
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
data:
  PREVIOUS_URL: {{ .Values.ingress.react.path }}
  # If PUBLIC_URL is "/" then metagrid expects it to be ""
  PUBLIC_URL: {{ ternary "" .Values.ingress.react.path (eq .Values.ingress.react.path "/") }}
  REACT_APP_METAGRID_API_URL: {{ include "metagrid.react.metagridUrl" . }}
  REACT_APP_PREVIOUS_URL: {{ .Values.previousURL }}
  {{- with .Values.external.globus }}
  REACT_APP_GLOBUS_REDIRECT: {{ .redirect }}
  REACT_APP_CLIENT_ID: {{ .clientID }}
  REACT_APP_GLOBUS_NODES: {{ .nodes }}
  {{- end }}
  REACT_APP_WGET_API_URL: {{ .Values.external.wget }}
  REACT_APP_SEARCH_URL: {{ .Values.external.search }}
  REACT_APP_ESGF_NODE_STATUS_URL: {{ .Values.external.nodeStatus }}
  {{- with .Values.external.keycloak }}
  REACT_APP_KEYCLOAK_REALM: {{ .realm }}
  REACT_APP_KEYCLOAK_URL: {{ .url }}
  REACT_APP_KEYCLOAK_CLIENT_ID: {{ .clientID }}
  {{- end }}
  {{- with .Values.external.hotjar }}
  REACT_APP_HOTJAR_ID: {{ .id | quote }}
  REACT_APP_HOTJAR_SV: {{ .sv | quote }}
  {{- end }}
  # TODO default metagrid nginx adds location for PREVIOUS_URL and breaks reverse proxy
  default.conf: |
    server {
      listen {{ .Values.react.service.port }};

      location ^~ {{ .Values.ingress.react.path }} {
        alias   /usr/share/nginx/html/;
        index  index.html index.htm;
        try_files $uri $uri/ {{ .Values.ingress.react.path }}/index.html;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
