apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metagrid.fullname" . }}-react
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
spec:
  {{- if not .Values.react.autoscaling.enabled }}
  replicas: {{ .Values.react.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metagrid.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: react
  template:
    metadata:
      {{- with .Values.react.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metagrid.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: react
    spec:
      imagePullSecrets:
      {{- range $name, $_ := .Values.imagePullSecrets }}
      - name: {{ include "metagrid.fullname" $ }}-{{ regexReplaceAll "\\W+" $name "-" }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.react.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.react.securityContext | nindent 12 }}
          image: "{{ .Values.react.image.repository }}:{{ .Values.react.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.react.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "metagrid.fullname" . }}-react
          env:
            {{- range $key, $value := (default dict .Values.react.env) }}
            - name: {{ tpl $key $ }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.react.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.ingress.react.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.ingress.react.path }}
              port: http
          resources:
            {{- toYaml .Values.react.resources | nindent 12 }}
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          # - name: nginx-conf
          #   mountPath: /usr/share/nginx/html/index.html
          #   subPath: index.html
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "metagrid.fullname" . }}-react
      {{- with .Values.react.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.react.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.react.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
