{{ if .Values.react.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "esgf-data-node.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
spec:
  selector:
    matchLabels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: http
    interval: 20s
    scheme: http
{{- end }}