{{- if .Values.ingress.enabled -}}
{{- $fullName := include "metagrid.fullname" . -}}
{{- with .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-react
  labels:
    {{- include "metagrid.labels" $ | nindent 4 }}
    app.kubernetes.io/component: react
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .react.host | quote }}
      http:
        paths:
          - path: {{ .react.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-react
                port:
                  number: {{ $.Values.react.service.port }}
    - host: {{ .django.host | quote }}
      http:
        paths:
          - path: {{ .django.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-django
                port:
                  number: {{ $.Values.django.service.port }}
{{- end }}
{{- end }}
