{{- if .Values.ingress.enabled -}}
{{- $fullName := include "metagrid.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-react
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
  {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-react
                port:
                  number: {{ .Values.react.service.port }}
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-django
                port:
                  number: {{ .Values.django.service.port }}
          - path: /accounts
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-django
                port:
                  number: {{ .Values.django.service.port }}
          - path: /proxy
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-django
                port:
                  number: {{ .Values.django.service.port }}
          - path: /account-confirm-email
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-django
                port:
                  number: {{ .Values.django.service.port }}
          - path: /swagger
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-django
                port:
                  number: {{ .Values.django.service.port }}
          - path: /redoc
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-django
                port:
                  number: {{ .Values.django.service.port }}
{{- end }}
