django:

  image:
    repository:
    tag: 

  env:
    DJANGO_ADMIN_URL: nimbus6.llnl.gov
    DOMAIN_NAME: esgf-.ornl.gov
    KEYCLOAK_URL: https://login.esgf.io/
    KEYCLOAK_REALM: esgf
    KEYCLOAK_CLIENT_ID: 
    DJANGO_SECRET_KEY: " nn4j8c3zyrjkvl9s2jxcx"
    PYTHONUNBUFFERED: "1"
    DJANGO_DEBUG: "True"
    REACT_APP_ESGF_NODE_URL: https://esgf-open.apps.onyx.ccs.ornl.gov/esg-search/search
    REACT_APP_WGET_API_URL: https://esgf-open.apps.onyx.ccs.ornl.gov/esg-search/wget
    REACT_APP_ESGF_NODE_STATUS_URL: https://aims2.llnl.gov/metagrid-backend/proxy/status

  ingress:
    enabled: true
    hosts:
    - host: nimbus6.llnl.gov
      paths:
      - path: /
        pathType: ImplementationSpecific

react:

  image:
    repository:
    tag: 

  env:
    REACT_APP_METAGRID_API_URL: https://{{ (index .Values.react.ingress.hosts 0).host }}/metagrid-backend
    REACT_APP_WGET_API_URL: https://esgf-node.llnl.gov/esg-search/wget
    REACT_APP_ESGF_NODE_URL: https://esgf-node.llnl.gov/esg-search/search
    REACT_APP_ESGF_NODE_STATUS_URL: https://aims2.llnl.gov/metagrid-backend/proxy/status
    REACT_APP_KEYCLOAK_REALM: esgf
    REACT_APP_KEYCLOAK_URL: https://login.esgf.io/
    REACT_APP_KEYCLOAK_CLIENT_ID: metagrid-llnl
    GENERATE_SOURCEMAP: 'false'
  
  ingress:
    enabled: true
    hosts:
    - host: nimbus6.llnl.gov
      paths:
      - path: /
        pathType: ImplementationSpecific

postgresql:
  persistence:
    enabled: false
  postgresql:
    replicaCount: 1
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    password: pgpass
    repmgrPassword: repmgrpass

  pgpool:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    adminPassword: pgpooladminpass

