django:
  env:
    DJANGO_ADMIN_URL: esgf-node.ccs.ornl.gov
    DOMAIN_NAME: esgf-node.ccs.ornl.gov
    KEYCLOAK_URL: https://login.esgf.io/
    KEYCLOAK_REALM: esgf
    KEYCLOAK_CLIENT_ID: metagrid-ornl
    DJANGO_SECRET_KEY: "2oop3rs3kr1t"
    PYTHONUNBUFFERED: "1"
    DJANGO_DEBUG: "True"
    REACT_APP_ESGF_NODE_URL: https://esgf-open.apps.onyx.ccs.ornl.gov/esg-search/search
    REACT_APP_WGET_API_URL: https://esgf-open.apps.onyx.ccs.ornl.gov/esg-search/wget
    REACT_APP_ESGF_NODE_STATUS_URL: https://aims2.llnl.gov/metagrid-backend/proxy/status

  ingress:
    enabled: false
    hosts:
    - host: esgf-node.ornl.gov
      paths:
      - path: /
        pathType: ImplementationSpecific

react:
  env:
    REACT_APP_METAGRID_API_URL: https://{{ (index .Values.react.ingress.hosts 0).host }}
    REACT_APP_WGET_API_URL: https://esgf-node.ornl.gov/esg-search/wget
    REACT_APP_ESGF_NODE_URL: https://esgf-node.ornl.gov/esg-search/search
    REACT_APP_ESGF_NODE_STATUS_URL: https://aims2.llnl.gov/metagrid-backend/proxy/status
    REACT_APP_KEYCLOAK_REALM: esgf
    REACT_APP_KEYCLOAK_URL: https://login.esgf.io/
    REACT_APP_KEYCLOAK_CLIENT_ID: metagrid-ornl
    GENERATE_SOURCEMAP: 'false'
  
  ingress:
    enabled: true
    annotations:
      ccs.ornl.gov/requireAuth: "false"
      route.openshift.io/termination: edge
    labels:
      ccs.ornl.gov/externalRoute: "true"
    hosts:
    - host: esgf-node.ornl.gov
      paths:
      - path: /
        pathType: ImplementationSpecific

postgresql:
  persistence:
    enabled: false
  postgresql:
    replicaCount: 1
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    password: pgpass
    repmgrPassword: repmgrpass

  pgpool:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    adminPassword: pgpooladminpass

extraManifests:
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: react
    namespace: cli137
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'react:latest'
    resources:
      limits:
        cpu: '4'
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 2Gi
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
    postCommit: {}
    source:
      type: Git
      dockerfile: |
        # Pull official base image
        FROM node:gallium-alpine3.15 as build

        # Set working directory
        WORKDIR /app

        # Add `/app/node_modules/.bin` to $PATH
        ENV PATH /app/node_modules/.bin:$PATH

        # Install app dependencies
        COPY package.json ./
        COPY yarn.lock ./
        RUN yarn install --verbose --frozen-lock-file --network-timeout=1000000

        # Add app
        COPY . ./

        RUN mv .envs/.react .envs/.prod.env

        RUN yarn build:production

        # Build production environment
        FROM nginxinc/nginx-unprivileged
        COPY docker/production/nginx/nginx.conf /etc/nginx/conf.d/default.conf
        COPY --from=build /app/build /usr/share/nginx/html
        COPY --from=build /app/docker/inject_runtime_env_vars.sh /docker-entrypoint.d/
        COPY --from=build /app/.envs/.prod.env /docker-entrypoint.d/

        CMD ["nginx-debug", "-g", "daemon off;"]

      git:
        uri: 'https://code.ornl.gov/does/esgf/metagrid.git'
        ref: ornl
      contextDir: frontend
    triggers:
      - type: ConfigChange
    runPolicy: Serial

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: react
    name: react
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: metagrid_production_react
        generation: null
        importPolicy: {}
        name: latest
        referencePolicy:
          type: ""

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: django
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: django:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: 'https://code.ornl.gov/does/esgf/metagrid.git'
        ref: ornl
      contextDir: backend
      dockerfile: |
        FROM python:3.9-slim-buster

        ENV PYTHONUNBUFFERED 1

        RUN apt-get update \
            # dependencies for building Python packages
            && apt-get install -y build-essential \
            # psycopg2 dependencies
            && apt-get install -y libpq-dev \
            # Translations dependencies
            && apt-get install -y gettext \
            # cleaning up unused files
            && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
            && rm -rf /var/lib/apt/lists/*

        RUN addgroup --system django \
            && adduser --system --ingroup django django

        # Requirements are installed here to ensure they will be cached.
        COPY ./requirements /requirements
        RUN pip install --no-cache-dir -r /requirements/production.txt django-extensions==3.1.5 \
            && rm -rf /requirements

        COPY --chown=django:django . /app

        USER django

        RUN python /app/manage.py collectstatic --noinput

        WORKDIR /app

        CMD ["/usr/local/bin/gunicorn", "config.wsgi", "--bind", "0.0.0.0:5000", "--chdir=/app", "--error-logfile=-", "--access-logfile=-", "--log-level=debug", "--capture-output", "--enable-stdio-inheritance"]

    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
        env:
        - name: DATABASE_URL
          value: '{{ include "metagrid.pg_uri" $ }}'
        - name: KEYCLOAK_URL
          value: https://keycloak.metagrid.com/auth
        - name: KEYCLOAK_REALM
          value: 'realm'
        - name: KEYCLOAK_CLIENT_ID
          value: 'client'
        - name: CORS_ORIGIN_WHITELIST
          value: 'whitelist'
    triggers:
      - type: ConfigChange

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: django
    name: django
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: metagrid_production_django
        generation: null
        importPolicy: {}
        name: latest
        referencePolicy:
          type: ""
