apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metagrid.fullname" . }}-django
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
data:
  {{- with .Values.django.gunicornCmdArgs }}
  GUNICORN_CMD_ARGS: {{ . | quote }}
  {{- end }}
  PYTHONBUFFERED: "1"
  DJANGO_DEBUG: {{ default "False" .Values.django.debug | quote }}
  DJANGO_ADMIN_URL: {{ .Values.django.adminURL }}
  DJANGO_ALLOWED_HOSTS: {{ include "metagrid.django_allowed_hosts" . }}
  DJANGO_SECURE_SSL_REDIRECT: "False"
  DJANGO_SETTINGS_MODULE: config.settings.production
  DOMAIN_NAME: {{ .Values.ingress.host }}
  DOMAIN_SUBDIRECTORY: {{ trimPrefix "/" .Values.ingress.django.path }}
  name: {{ include "metagrid.fullname" . }}-django
  CORS_ORIGIN_WHITELIST: {{ default (printf "http://%v-react:%v" (include "metagrid.fullname" .) .Values.react.service.port) .Values.django.corsOriginWhitelist }}
  KEYCLOAK_URL: {{ .Values.external.keycloak.url }}
  KEYCLOAK_REALM: {{ .Values.external.keycloak.realm }}
  KEYCLOAK_CLIENT_ID: {{ .Values.external.keycloak.clientID }}
  REACT_APP_WGET_API_URL: {{ .Values.external.wget }}
  REACT_APP_SEARCH_URL: {{ .Values.external.search }}
  REACT_APP_ESGF_NODE_STATUS_URL: {{ default (printf "https://%v/%v/proxy/status" .Values.ingress.django.host .Values.ingress.django.path) .Values.external.nodeStatus }}
  REACT_APP_ESGF_SOLR_URL: {{ .Values.external.solr }}
  POSTGRES_HOST: {{ include "metagrid.pg_host" . }}
  POSTGRES_PORT: {{ include "metagrid.pg_port" . | quote }}
