apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metagrid.fullname" . }}-django
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
data:
  PYTHONBUFFERED: "1"
  DJANGO_DEBUG: {{ defult "False" .Values.django.debug }}
  DJANGO_ADMIN_URL: {{ .Values.django.adminURL }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.django.allowedHosts }}
  DJANGO_SECURE_SSL_REDIRECT: "False"
  DJANGO_SETTINGS_MODULE: config.settings.production
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey }}
  DOMAIN_NAME: {{ .Values.ingress.host }}
  DOMAIN_SUBDIRECTORY: {{ .Values.ingress.django.path }}
  CORS_ORIGIN_WHITELIST: {{ .Values.django.corsOriginWhitelist }}
  KEYCLOAK_URL: {{ .Values.external.keycloak.url }}
  KEYCLOAK_REALM: {{ .Values.external.keycloak.realm }}
  KEYCLOAK_CLIENT_ID: {{ .Values.external.keycloak.clientID }}
  REACT_APP_WGET_API_URL: {{ .Values.external.wget }}
  REACT_APP_SEARCH_URL: {{ .Values.external.search }}
  REACT_APP_ESGF_NODE_STATUS_URL: {{ .Values.external.nodeStatus }}
  REACT_APP_ESGF_SOLR_URL: {{ .Values.external.solr }}
  DATABASE_URL: {{ include "metagrid.pg_uri" . }}
  POSTGRES_DB: {{ include "metagrid.pg_db" . }}
  POSTGRES_USER: {{ include "metagrid.pg_user" . }}
  POSTGRES_PASSWORD: {{ include "metagrid.pg_pass" . }}
  POSTGRES_HOST: {{ include "metagrid.pg_host" . }}
  POSTGRES_PORT: {{ include "metagrid.pg_port" . | quote }}
