apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metagrid.fullname" . }}-django
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
data:
  {{- with .Values.django.gunicornCmdArgs }}
  GUNICORN_CMD_ARGS: {{ . | quote }}
  {{- end }}
  PYTHONBUFFERED: "1"
  DJANGO_DEBUG: {{ .Values.django.debug | quote }}
  DJANGO_ADMIN_URL: {{ .Values.django.adminUrl }}
  DJANGO_ALLOWED_HOSTS: {{ include "metagrid.djangoAllowedHosts" . | quote }}
  DJANGO_SECURE_SSL_REDIRECT: "False"
  DJANGO_SETTINGS_MODULE: config.settings.production
  DJANGO_LOGIN_REDIRECT_URL: {{ include "metagrid.django.loginRedirect" . | quote }}
  DJANGO_LOGOUT_REDIRECT_URL: {{ include "metagrid.django.logoutRedirect" . | quote }}
  GLOBUS_CLIENT_KEY: {{ .Values.globus.clientID }}
  DOMAIN_NAME: {{ default "127.0.0.1" .Values.ingress.django.host }}
  DOMAIN_SUBDIRECTORY: {{ trimPrefix "/" .Values.django.urlPath }}
  CORS_ALLOWED_ORIGINS: {{ include "metagrid.django.corsOriginWhitelist" . }}
  # CORS_ORIGIN_WHITELIST: {{ include "metagrid.django.corsOriginWhitelist" . }}
  {{- if eq .Values.authType "globus" }}
  GLOBUS_CLIENT_KEY: {{ .Values.globus.backend.clientID }}
  {{- end }}
  KEYCLOAK_URL: {{ default "" .Values.keyCloak.url }}
  KEYCLOAK_REALM: {{ default "" .Values.keyCloak.realm }}
  KEYCLOAK_CLIENT_ID: {{ default "" .Values.keyCloak.clientID }}
  REACT_APP_WGET_API_URL: {{ .Values.wgetApiUrl }}
  REACT_APP_SEARCH_URL: {{ .Values.searchUrl }}
  REACT_APP_ESGF_NODE_STATUS_URL: {{ .Values.esgfNodeStatusUrl }}
  REACT_APP_ESGF_SOLR_URL: {{ .Values.solrUrl }}

  # Add DB6-related environment variables
  DB6_HOST: {{ .Values.db6.host | default "db6.ceda.ac.uk" }}
  DB6_PORT: {{ .Values.db6.port | default "5432" | quote }}
  DB6_USER: {{ .Values.db6.user }}
  DB6_PASSWORD: {{ .Values.db6.password }}
  DB6_DB: {{ .Values.db6.database | default }}
  USE_DB6: {{ .Values.db6.enabled | default }}


  POSTGRES_HOST: {{ include "metagrid.pg_host" . }}
  POSTGRES_PORT: {{ include "metagrid.pg_port" . | quote }}
