apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metagrid.fullname" . }}-django
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
data:
  {{- if eq .Values.authType "globus" }}
  GLOBUS_CLIENT_SECRET: {{ default "" .Values.globus.backend.clientSecret | b64enc }}
  {{- end }}
  DJANGO_SECRET_KEY: {{ default (randBytes 50) .Values.django.secretKey | b64enc }}
  DATABASE_URL: {{ include "metagrid.pg_uri" . | b64enc }}
  POSTGRES_DB: {{ include "metagrid.pg_db" . | b64enc }}
  POSTGRES_USER: {{ include "metagrid.pg_user" . | b64enc }}
  POSTGRES_PASSWORD: {{ include "metagrid.pg_pass" . | b64enc }}
  {{- if .Values.django.admin.create }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.django.admin.username | b64enc }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.django.admin.password | b64enc }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.django.admin.email | b64enc }}
  {{- end }}
