{{- if .Values.django.migrateJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-django-migrate
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate-job
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.django.podAnnotations }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  backoffLimit: 0
  template:
    spec:
      {{- $django := deepCopy .Values.django }}
      {{- $_ := set $django "name" "migrate" }}
      {{- $_ := set $django.image "pullSecrets" .Values.imagePullSecrets }}
      {{- $_ := set $django "args" (list "python" "manage.py" "migrate" "--settings=$(DJANGO_SETTINGS_MODULE)") }}
      {{- $config := dict "configMapRef" (dict "name" (printf "%s-django" (include "metagrid.fullname" .))) }}
      {{- $secret := dict "secretRef" (dict "name" (printf "%s-django" (include "metagrid.fullname" .))) }}
      {{- $_ := set $django "envFrom" (list $config $secret) }}
      {{- $_ := set $django "TemplateValues" . }}
      {{- include "metagrid.podSpec" $django | nindent 6 }}
{{- end -}}
